### ISSUE TITLE
wrong GPU working

### ISSUE THREAD

**Issue by EtWnn** [vertcoin-project/one-click-miner-vnext#150]
I have two GPUs, one Intel HD for display and one NVIDIA Geforce for high performance. When launching the miner, only the weakest one (Intel) works and I did not find a way to make the miner use the Geforce card.

Is there any way to configure which card to attach to the mining process?

**Comment by ironcladmerc** [comment]
same issue here. it should use the nVidia GPU. this should at minimum be configurable

**Comment by vertiond** [comment]
Could you please paste your debug.log from %appdata%\vertcoin-ocm

The One Click Miner will try to use all GPUs by default and there is no way to change that.  There is an enhancement label here: https://github.com/vertcoin-project/one-click-miner-vnext/issues/128#issuecomment-774773200 to disable integrated graphics (Intel HD) which may solve this problem.

**Comment by descawed** [comment]
I also noticed that Task Manager shows my Intel GPU at 100% and my NVIDIA GPU at 0%. But in the logs, I see that the miner did detect both GPUs and mentioned configuring 1 CL and 1 CUDA worker. If cl_device(0) and cu_device(1) in the logs correspond to my GPU 0 and GPU 1, then it would seem that both GPUs are being used. Could it be that Task Manager simply isn't showing the NVIDIA usage for some reason? Below are relevant parts of the log:

```
2021/02/15 11:48:41.483176 [DEBUG] GPU [NVIDIA GeForce RTX 3090] matched regex [.*NVIDIA.*]
2021/02/15 11:48:41.483176 [DEBUG] GPU [Intel(R) UHD Graphics 630] matched regex [.*Intel.*]
2021/02/15 11:48:41.542148 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/02/15 11:48:41.542148 [DEBUG] Found compatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/02/15 11:48:41.542148 [DEBUG] Not adding already present multi-gpu binary [VerthashMiner.exe] again
2021/02/15 11:48:41.542148 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/02/15 11:48:41.542148 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/02/15 11:48:41.542148 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/02/15 11:48:41.542148 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/1] (Closed source: false)
2021/02/15 11:48:41.542148 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/3] (Closed source: false)
2021/02/15 11:48:41.542148 [DEBUG] Found incompatible binary [VerthashMiner.exe] for [windows/2] (Closed source: false)
2021/02/15 11:48:41.542148 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/1] (Closed source: false)
2021/02/15 11:48:41.542148 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/3] (Closed source: false)
2021/02/15 11:48:41.542148 [DEBUG] Found incompatible binary [VerthashMiner] for [linux/2] (Closed source: false)
2021/02/15 11:48:41.542148 [DEBUG] [Miner windows/3]Binary not found, downloading...
2021/02/15 11:48:41.851691 [DEBUG] [Miner windows/3]Daemon file downloaded
2021/02/15 11:48:41.862690 [DEBUG] [Miner windows/3]Daemon file is available and correct
2021/02/15 11:48:41.862690 [DEBUG] [Miner windows/3](Re)creating unpack directory
...
2021/02/15 12:03:03.403976 [DEBUG] [VerthashMiner] [2021-02-15 12:03:03] WARN  Skipping CL platform (index: 0, NVIDIA Corporation)
2021/02/15 12:03:03.403976 [DEBUG] [VerthashMiner] [2021-02-15 12:03:03] INFO  Found 1 OpenCL devices.
2021/02/15 12:03:03.431976 [DEBUG] [VerthashMiner] [2021-02-15 12:03:03] INFO  Found 1 CUDA devices
2021/02/15 12:03:03.431976 [DEBUG] [VerthashMiner] [2021-02-15 12:03:03] INFO  Configuration file device list format: "raw device list"
2021/02/15 12:03:03.431976 [DEBUG] [VerthashMiner] [2021-02-15 12:03:03] WARN  All possible OpenCL device/platform combinations will be listed.
...
2021/02/15 12:03:10.648364 [DEBUG] [VerthashMiner] [2021-02-15 12:03:10] INFO  Configured 1(CL) and 1(CUDA) workers
2021/02/15 12:03:10.651364 [DEBUG] [VerthashMiner] [2021-02-15 12:03:10] INFO  2 miner threads started, using Verthash algorithm.
2021/02/15 12:03:10.651364 [DEBUG] [VerthashMiner] [2021-02-15 12:03:10] INFO  Starting Stratum on stratum+tcp://vertcoin.hashalot.net:3950
2021/02/15 12:03:10.840393 [DEBUG] [VerthashMiner] [2021-02-15 12:03:10] INFO  Stratum difficulty set to 1
2021/02/15 12:03:10.865363 [DEBUG] [VerthashMiner] [2021-02-15 12:03:10] INFO  Verthash block: 1509838
2021/02/15 12:03:11.066363 [DEBUG] [VerthashMiner] [2021-02-15 12:03:11] INFO  cu_device(0): WorkSize has been set to: 131072
2021/02/15 12:03:13.975617 [DEBUG] [VerthashMiner] [2021-02-15 12:03:13] INFO  cl_device(0): WorkSize has been set to: 131072
2021/02/15 12:03:15.130590 [DEBUG] [VerthashMiner] [2021-02-15 12:03:15] INFO  cu_device(1): hashrate: 1710.75 kH/s
2021/02/15 12:03:15.130590 [DEBUG] Device IDX: 1
2021/02/15 12:03:16.441590 [DEBUG] [VerthashMiner] [2021-02-15 12:03:16] INFO  Verthash block: 1509839
2021/02/15 12:03:19.197626 [DEBUG] [VerthashMiner] [2021-02-15 12:03:19] INFO  cu_device(1): hashrate: 1708.86 kH/s
2021/02/15 12:03:19.197626 [DEBUG] Device IDX: 1
2021/02/15 12:03:19.832617 [DEBUG] [VerthashMiner] [2021-02-15 12:03:19] INFO  cl_device(0): hashrate: 44.77 kH/s
2021/02/15 12:03:19.832617 [DEBUG] Device IDX: 0
```

**Comment by ironcladmerc** [comment]
that's what I'm seeing in my log as well, it does seem to be using both GPUs, but Task Manager only shows usage on the integrated GPU for some reason.

**Comment by EtWnn** [comment]
Here are my logs. 
I have exactly the same behavior  as @ironcladmerc  and @descawed: The task manager says that only the intel card is working.
```
2021/02/14 08:59:22.025950 [DEBUG] [Miner windows/3]Daemon file is available and correct
2021/02/14 08:59:22.025950 [DEBUG] [Miner windows/3](Re)creating unpack directory
2021/02/14 09:23:27.354385 [DEBUG] Launching C:\Users\<User>\AppData\Roaming\vertcoin-ocm\miners\unpacked-feee1d16d7405ef07d17203c3afef5b3217c4f4de84616ecc095f74014edb598\VerthashMiner-0.6.2-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\<User>\AppData\Roaming\vertcoin-ocm\verthash-miner-tmpl.conf]
2021/02/14 09:23:28.550758 [DEBUG] [VerthashMiner] [2021-02-14 09:23:28] WARN  Skipping CL platform (index: 0, NVIDIA Corporation)
2021/02/14 09:23:28.550758 [DEBUG] [VerthashMiner] [2021-02-14 09:23:28] INFO  Found 1 OpenCL devices.
2021/02/14 09:23:28.945447 [DEBUG] [VerthashMiner] [2021-02-14 09:23:28] INFO  Found 1 CUDA devices
2021/02/14 09:23:28.946444 [DEBUG] [VerthashMiner] [2021-02-14 09:23:28] INFO  Configuration file device list format: "raw device list"
2021/02/14 09:23:28.946444 [DEBUG] [VerthashMiner] [2021-02-14 09:23:28] WARN  All possible OpenCL device/platform combinations will be listed.
2021/02/14 09:23:28.953426 [DEBUG] [VerthashMiner] [2021-02-14 09:23:28] INFO  Configuration file: (C:\Users\<User>\AppData\Roaming\vertcoin-ocm\verthash-miner-tmpl.conf) has been generated.
2021/02/14 09:23:29.027641 [DEBUG] AvailableGPUs called
2021/02/14 09:23:29.028640 [DEBUG] Launching C:\Users\<User>\AppData\Roaming\vertcoin-ocm\miners\unpacked-feee1d16d7405ef07d17203c3afef5b3217c4f4de84616ecc095f74014edb598\VerthashMiner-0.6.2-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\<User>\AppData\Roaming\vertcoin-ocm\verthash-miner-tmp.conf]
2021/02/14 09:23:29.180293 [DEBUG] [VerthashMiner] [2021-02-14 09:23:29] WARN  Skipping CL platform (index: 0, NVIDIA Corporation)
2021/02/14 09:23:29.180293 [DEBUG] [VerthashMiner] [2021-02-14 09:23:29] INFO  Found 1 OpenCL devices.
2021/02/14 09:23:29.203258 [DEBUG] [VerthashMiner] [2021-02-14 09:23:29] INFO  Found 1 CUDA devices
2021/02/14 09:23:29.203258 [DEBUG] [VerthashMiner] [2021-02-14 09:23:29] INFO  Configuration file device list format: "raw device list"
2021/02/14 09:23:29.203258 [DEBUG] [VerthashMiner] [2021-02-14 09:23:29] WARN  All possible OpenCL device/platform combinations will be listed.
2021/02/14 09:23:29.205188 [DEBUG] [VerthashMiner] [2021-02-14 09:23:29] INFO  Configuration file: (C:\Users\<User>\AppData\Roaming\vertcoin-ocm\verthash-miner-tmp.conf) has been generated.
2021/02/14 09:23:30.133928 [INFO] Starting mining process...
2021/02/14 09:23:30.134691 [INFO] Updating balance...
2021/02/14 09:23:30.134691 [DEBUG] [Miner windows/3]Daemon file already exists
2021/02/14 09:23:30.139674 [DEBUG] [Miner windows/3]Daemon file is available and correct
2021/02/14 09:23:30.139674 [DEBUG] [Miner windows/3]Removing unpack directory
2021/02/14 09:23:30.143664 [DEBUG] [Miner windows/3](Re)creating unpack directory
2021/02/14 09:23:30.257359 [DEBUG] AvailableGPUs called
2021/02/14 09:23:30.258356 [DEBUG] Launching C:\Users\<User>\AppData\Roaming\vertcoin-ocm\miners\unpacked-feee1d16d7405ef07d17203c3afef5b3217c4f4de84616ecc095f74014edb598\VerthashMiner-0.6.2-CUDA11-windows\VerthashMiner.exe [--gen-conf C:\Users\<User>\AppData\Roaming\vertcoin-ocm\verthash-miner-tmp.conf]
2021/02/14 09:23:30.463806 [DEBUG] [VerthashMiner] [2021-02-14 09:23:30] WARN  Skipping CL platform (index: 0, NVIDIA Corporation)
2021/02/14 09:23:30.463806 [DEBUG] [VerthashMiner] [2021-02-14 09:23:30] INFO  Found 1 OpenCL devices.
2021/02/14 09:23:30.486746 [DEBUG] [VerthashMiner] [2021-02-14 09:23:30] INFO  Found 1 CUDA devices
2021/02/14 09:23:30.486746 [DEBUG] [VerthashMiner] [2021-02-14 09:23:30] INFO  Configuration file device list format: "raw device list"
2021/02/14 09:23:30.487757 [DEBUG] [VerthashMiner] [2021-02-14 09:23:30] WARN  All possible OpenCL device/platform combinations will be listed.
2021/02/14 09:23:30.489737 [DEBUG] [VerthashMiner] [2021-02-14 09:23:30] INFO  Configuration file: (C:\Users\<User>\AppData\Roaming\vertcoin-ocm\verthash-miner-tmp.conf) has been generated.
2021/02/14 09:23:30.558897 [DEBUG] Launching C:\Users\<User>\AppData\Roaming\vertcoin-ocm\miners\unpacked-feee1d16d7405ef07d17203c3afef5b3217c4f4de84616ecc095f74014edb598\VerthashMiner-0.6.2-CUDA11-windows\VerthashMiner.exe [--conf C:\Users\<User>\AppData\Roaming\vertcoin-ocm\verthash-miner.conf]
2021/02/14 09:23:30.650614 [DEBUG] Nethash: 1574845372
2021/02/14 09:23:30.703475 [DEBUG] [VerthashMiner] [2021-02-14 09:23:30] WARN  Skipping CL platform (index: 0, NVIDIA Corporation)
2021/02/14 09:23:30.703475 [DEBUG] [VerthashMiner] [2021-02-14 09:23:30] INFO  Found 1 OpenCL devices.
2021/02/14 09:23:30.725414 [DEBUG] [VerthashMiner] [2021-02-14 09:23:30] INFO  Found 1 CUDA devices
2021/02/14 09:23:30.726412 [DEBUG] [VerthashMiner] [2021-02-14 09:23:30] INFO  Using a configuration file (C:\Users\<User>\AppData\Roaming\vertcoin-ocm\verthash-miner.conf)
2021/02/14 09:23:30.726412 [DEBUG] [VerthashMiner] [2021-02-14 09:23:30] INFO  Loading verthash data file...
2021/02/14 09:23:31.212164 [INFO] Updating balance...
2021/02/14 09:23:31.353732 [DEBUG] [VerthashMiner] [2021-02-14 09:23:31] INFO  Verthash data file has been loaded succesfully!
2021/02/14 09:23:31.353732 [DEBUG] [VerthashMiner] [2021-02-14 09:23:31] INFO  Verifying verthash data file...
2021/02/14 09:23:38.670038 [DEBUG] [VerthashMiner] [2021-02-14 09:23:38] INFO  Verthash data file has been verified succesfully!
2021/02/14 09:23:38.670038 [DEBUG] [VerthashMiner] [2021-02-14 09:23:38] INFO  Using protocol: Stratum.
2021/02/14 09:23:38.671036 [DEBUG] [VerthashMiner] [2021-02-14 09:23:38] WARN  Failed to get a "CoinbaseAddress" option inside "Connection" section. Setting to ""
2021/02/14 09:23:38.671036 [DEBUG] [VerthashMiner] [2021-02-14 09:23:38] WARN  Failed to get a "CoinbaseSignature" option inside "Connection" section. Setting to ""
2021/02/14 09:23:38.672034 [DEBUG] [VerthashMiner] [2021-02-14 09:23:38] WARN  Failed to get a "SSLCertificateFileName" option inside "Connection" section. Setting to ""
2021/02/14 09:23:38.672034 [DEBUG] [VerthashMiner] [2021-02-14 09:23:38] WARN  Failed to get a "Proxy" option inside "Connection" section. Setting to ""
2021/02/14 09:23:38.673030 [DEBUG] [VerthashMiner] [2021-02-14 09:23:38] WARN  Failed to get a "Redirect" option inside "Connection" section. Setting to "true"
2021/02/14 09:23:38.673030 [DEBUG] [VerthashMiner] [2021-02-14 09:23:38] WARN  Failed to get a "LongPoll" option inside "Connection" section. Setting to "true"
2021/02/14 09:23:38.673030 [DEBUG] [VerthashMiner] [2021-02-14 09:23:38] WARN  Failed to get a "LongPollTimeout" option inside "Connection" section. Setting to "0"
2021/02/14 09:23:38.674027 [DEBUG] [VerthashMiner] [2021-02-14 09:23:38] WARN  Failed to get a "Scantime" option inside "Connection" section. Setting to "5"
2021/02/14 09:23:38.674027 [DEBUG] [VerthashMiner] [2021-02-14 09:23:38] WARN  Failed to get a "Retries" option inside "Connection" section. Setting to "-1"
2021/02/14 09:23:38.674027 [DEBUG] [VerthashMiner] [2021-02-14 09:23:38] WARN  Failed to get a "RetryPause" option inside "Connection" section. Setting to "5"
2021/02/14 09:23:38.675039 [DEBUG] [VerthashMiner] [2021-02-14 09:23:38] WARN  Failed to get a "ProtocolDump" option inside "Connection" section. Setting to "false"
2021/02/14 09:23:38.675039 [DEBUG] [VerthashMiner] [2021-02-14 09:23:38] INFO  Miner has been successfully configured! (Errors: 0, Warnings: 11)
2021/02/14 09:23:38.675039 [DEBUG] [VerthashMiner] [2021-02-14 09:23:38] INFO  Configured 1(CL) and 1(CUDA) workers
2021/02/14 09:23:38.680013 [DEBUG] [VerthashMiner] [2021-02-14 09:23:38] INFO  2 miner threads started, using Verthash algorithm.
2021/02/14 09:23:38.680013 [DEBUG] [VerthashMiner] [2021-02-14 09:23:38] INFO  Starting Stratum on stratum+tcp://vertcoin.hashalot.net:3950
2021/02/14 09:23:38.994171 [DEBUG] [VerthashMiner] [2021-02-14 09:23:38] INFO  Stratum difficulty set to 1
2021/02/14 09:23:38.994171 [DEBUG] [VerthashMiner] [2021-02-14 09:23:38] INFO  Verthash block: 1508969
2021/02/14 09:23:39.309331 [DEBUG] [VerthashMiner] [2021-02-14 09:23:39] INFO  cu_device(0): WorkSize has been set to: 131072
2021/02/14 09:23:40.359629 [DEBUG] [VerthashMiner] fcl build 1 succeeded.
2021/02/14 09:23:40.359629 [DEBUG] [VerthashMiner] bcl build succeeded.
2021/02/14 09:23:40.359629 [DEBUG] [VerthashMiner] 
2021/02/14 09:23:40.780503 [DEBUG] [VerthashMiner] fcl build 1 succeeded.
2021/02/14 09:23:40.780503 [DEBUG] [VerthashMiner] bcl build succeeded.
2021/02/14 09:23:40.780503 [DEBUG] [VerthashMiner] 
2021/02/14 09:23:41.424781 [DEBUG] [VerthashMiner] fcl build 1 succeeded.
2021/02/14 09:23:41.425778 [DEBUG] [VerthashMiner] bcl build succeeded.
2021/02/14 09:23:41.425778 [DEBUG] [VerthashMiner] 
2021/02/14 09:23:41.425778 [DEBUG] [VerthashMiner] [2021-02-14 09:23:41] INFO  cl_device(0): WorkSize has been set to: 131072
2021/02/14 09:23:44.230735 [DEBUG] [VerthashMiner] [2021-02-14 09:23:44] INFO  cu_device(1): hashrate: 79.92 kH/s
2021/02/14 09:23:44.230735 [DEBUG] Device IDX: 1
2021/02/14 09:23:46.315204 [DEBUG] [VerthashMiner] [2021-02-14 09:23:46] INFO  cl_device(0): hashrate: 26.81 kH/s
2021/02/14 09:23:46.315204 [DEBUG] Device IDX: 0
2021/02/14 09:23:49.150578 [DEBUG] [VerthashMiner] [2021-02-14 09:23:49] INFO  cu_device(1): hashrate: 79.92 kH/s
2021/02/14 09:23:49.151593 [DEBUG] Device IDX: 1
2021/02/14 09:23:50.913717 [DEBUG] [VerthashMiner] [2021-02-14 09:23:50] INFO  cl_device(0): hashrate: 27.63 kH/s
2021/02/14 09:23:50.913717 [DEBUG] Device IDX: 0
2021/02/14 09:23:54.072063 [DEBUG] [VerthashMiner] [2021-02-14 09:23:54] INFO  cu_device(1): hashrate: 79.91 kH/s
2021/02/14 09:23:54.072063 [DEBUG] Device IDX: 1
```

> There is an enhancement label here: #128 (comment) to disable integrated graphics (Intel HD) which may solve this problem.

Thanks, I will look into that

**Comment by vertiond** [comment]
I see hashrate from both cl_device(0) and cu_device(1).  They seem to both be working.

**Comment by descawed** [comment]
I've done some more research and this appears to just be an issue with how Task Manager displays CUDA usage. For me, when viewing a GPU in Task Manager, it displays 4 charts at the top - 3D, Copy, Video Encode, and Video Decode. It turns out these are just 4 options of a couple dozen different things you can have it display. If I click the text above the chart that says (for example) "3D", one of the options in the dropdown is Cuda, and if I choose that I do see 100% on my NVIDIA GPU. So I believe there's no issue with the miner, we've just been fooled by the perhaps unintuitive behavior of Task Manager.

**Comment by EtWnn** [comment]
OK thanks you all for your investigation! I will then close this issue as both GPUs seems to be working correctly.

**Comment by CharaD7** [comment]
Sorry, I have the same issue on my ubuntu 22.04 OS. I updated my vertcoin ocm just a week ago

`
2024/07/27 07:23:32.975672 OCM v2.2-0-g27859cb Started up
2024/07/27 07:23:32.975821 [ERROR] Error in getSetting(testnet): not found
2024/07/27 07:23:32.975848 [ERROR] Error in getSetting(testnet): not found
2024/07/27 07:23:32.975891 [INFO] Finding best P2Pool node...
2024/07/27 07:23:32.975963 [ERROR] Error in getSetting(testnet): not found
2024/07/27 07:23:32.976089 [INFO] No local node detected, selecting other public nodes

(vertcoin-ocm:156535): Gtk-WARNING **: 07:23:33.001: Theme parsing error: gtk.css:6583:68: Invalid name of pseudo-class
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
2024/07/27 07:23:33.392316 [WARN]Error: Check if you are connected to the internet
2024/07/27 07:23:33.392334 [WARN]listen ip4:icmp : socket: operation not permitted
2024/07/27 07:23:33.392924 [WARN]Error: Check if you are connected to the internet
2024/07/27 07:23:33.392938 [WARN]listen ip4:icmp : socket: operation not permitted
2024/07/27 07:23:33.399631 [WARN]Error: Check if you are connected to the internet
2024/07/27 07:23:33.399647 [WARN]listen ip4:icmp : socket: operation not permitted
2024/07/27 07:23:33.400323 [WARN]Error: Check if you are connected to the internet
2024/07/27 07:23:33.400334 [WARN]listen ip4:icmp : socket: operation not permitted
2024/07/27 07:23:33.401719 [WARN]Error: Check if you are connected to the internet
2024/07/27 07:23:33.401730 [WARN]listen ip4:icmp : socket: operation not permitted
2024/07/27 07:23:33.401867 [WARN]Error: Check if you are connected to the internet
2024/07/27 07:23:33.401872 [WARN]listen ip4:icmp : socket: operation not permitted

(WebKitWebProcess:156580): Gtk-WARNING **: 07:23:33.417: Theme parsing error: gtk.css:6583:68: Invalid name of pseudo-class

(WebKitWebProcess:156580): Gtk-WARNING **: 07:23:33.445: Theme parsing error: gtk.css:6583:68: Invalid name of pseudo-class
panic: sync: negative WaitGroup counter

goroutine 191 [running]:
sync.(*WaitGroup).Add(0xc00002dd40?, 0x3a?)
        /usr/local/go/src/sync/waitgroup.go:62 +0xd8
sync.(*WaitGroup).Done(...)
        /usr/local/go/src/sync/waitgroup.go:87
github.com/wailsapp/wails/lib/renderer.(*WebView).evalJSSync.func1.1({0xc000256690?, 0xc0003261d0?, 0xc0003261c8?})
        /home/kg/go/pkg/mod/github.com/wailsapp/wails@v1.16.9/lib/renderer/webview.go:193 +0xc5
created by github.com/wailsapp/wails/lib/event.(*Manager).Start.func1 in goroutine 84
        /home/kg/go/pkg/mod/github.com/wailsapp/wails@v1.16.9/lib/event/manager.go:151 +0x4fa
`
