### ISSUE TITLE
OCM crash report

### ISSUE THREAD

**Issue by ac0uk** [vertcoin-project/one-click-miner-vnext#95]
My OCM had crashed. I was running the debug build. alpha8 on Windows 10

```
fatal error: concurrent map iteration and map write
2020/12/28 16:34:49.843693 [DEBUG] [VerthashMiner] [2020-12-28 16:34:49] INFO  accepted: 159009/256158 (62.07%), total hashrate: 1237.56 kH/s

goroutine 12609 [running]:
runtime.throw(0x1535f6a, 0x26)
        c:/go/src/runtime/panic.go:1116 +0x79 fp=0xc00024fd30 sp=0xc00024fd00 pc=0xeca4d9
runtime.mapiternext(0xc00024fdf8)
        c:/go/src/runtime/map.go:853 +0x56c fp=0xc00024fdb0 sp=0xc00024fd30 pc=0xea262c
runtime.mapiterinit(0x1488d40, 0xc0005b2630, 0xc00024fdf8)
        c:/go/src/runtime/map.go:843 +0x1da fp=0xc00024fdd0 sp=0xc00024fdb0 pc=0xea1fda
github.com/vertcoin-project/one-click-miner-vnext/miners.(*VerthashMinerImpl).HashRate(0xc0004f0bf0, 0xc00024fed4)
        C:/src/one-click-miner-vnext/miners/verthashminer.go:109 +0x92 fp=0xc00024fe68 sp=0xc00024fdd0 pc=0x126b952
github.com/vertcoin-project/one-click-miner-vnext/miners.(*BinaryRunner).HashRate(...)
        C:/src/one-click-miner-vnext/miners/miners.go:195
github.com/vertcoin-project/one-click-miner-vnext/backend.(*Backend).StartMining.func2(0xc00029e000)
        C:/src/one-click-miner-vnext/backend/mining.go:76 +0x7c fp=0xc00024ffd8 sp=0xc00024fe68 pc=0x1379e3c
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00024ffe0 sp=0xc00024ffd8 pc=0xefcca1
created by github.com/vertcoin-project/one-click-miner-vnext/backend.(*Backend).StartMining
        C:/src/one-click-miner-vnext/backend/mining.go:62 +0x18a

goroutine 1 [syscall, locked to thread]:
github.com/wailsapp/wails/lib/renderer/webview._Cfunc_CgoWebViewLoop(0x1bdfaee18f0, 0x1bd00000001, 0x0)
        _cgo_gotypes.go:174 +0x54
github.com/wailsapp/wails/lib/renderer/webview.(*webview).Loop.func1(0xc0001da040, 0x1, 0xc000000000)
        C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/renderer/webview/webview.go:279 +0x65
github.com/wailsapp/wails/lib/renderer/webview.(*webview).Loop(0xc0001da040, 0x1, 0x1)
        C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/renderer/webview/webview.go:279 +0x3b
github.com/wailsapp/wails/lib/renderer/webview.(*webview).Run(0xc0001da040)
        C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/renderer/webview/webview.go:283 +0x37
github.com/wailsapp/wails/lib/renderer.(*WebView).Run(0xc0001e6000, 0x1791840, 0xc0001e6000)
        C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/renderer/webview.go:232 +0x1ce
github.com/wailsapp/wails.(*App).start(0xc0004ba080, 0x0, 0x0)
        C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/app.go:145 +0x5ab
github.com/wailsapp/wails/cmd.(*Command).Run(0xc0001ea0b0, 0xc00003c1c0, 0x0, 0x0, 0x1709a00, 0x1)
        C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/cmd/cli.go:170 +0xd9
github.com/wailsapp/wails/cmd.(*Cli).Run(0xc0001e5320, 0x0, 0x0, 0x0, 0x132844f, 0x147dd80)
        C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/cmd/cli.go:47 +0x9d
github.com/wailsapp/wails.(*App).Run(0xc0004ba080, 0x1508dc0, 0xc00029e000)
        C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/app.go:89 +0x5c
main.main()
        C:/src/one-click-miner-vnext/main.go:89 +0x69d

goroutine 36 [chan receive, 12674 minutes]:
github.com/vertcoin-project/one-click-miner-vnext/backend.(*Backend).PrerequisiteProxyLoop(0xc00029e000)
        C:/src/one-click-miner-vnext/backend/settings.go:86 +0x95
created by github.com/vertcoin-project/one-click-miner-vnext/backend.(*Backend).WailsInit
        C:/src/one-click-miner-vnext/backend/backend.go:68 +0x5d

goroutine 20 [chan receive, 9982 minutes]:
github.com/vertcoin-project/one-click-miner-vnext/tracking.StartTracker.func1(0xc000086099, 0xc0004c3f80)
        C:/src/one-click-miner-vnext/tracking/matomo.go:70 +0xa5
created by github.com/vertcoin-project/one-click-miner-vnext/tracking.StartTracker
        C:/src/one-click-miner-vnext/tracking/matomo.go:68 +0xd4

goroutine 50 [chan receive]:
github.com/tidwall/buntdb.(*DB).backgroundManager(0xc0001ea160)
        C:/Users/build/go/pkg/mod/github.com/tidwall/buntdb@v1.1.0/buntdb.go:548 +0xca
created by github.com/tidwall/buntdb.Open
        C:/Users/build/go/pkg/mod/github.com/tidwall/buntdb@v1.1.0/buntdb.go:171 +0x2e5

goroutine 52 [syscall, 12674 minutes]:
os/signal.signal_recv(0x178c060)
        c:/go/src/runtime/sigqueue.go:147 +0xa9
os/signal.loop()
        c:/go/src/os/signal/signal_unix.go:23 +0x29
created by os/signal.Notify.func1.1
        c:/go/src/os/signal/signal.go:150 +0x4b

goroutine 12631 [select, 9982 minutes]:
io.(*pipe).Read(0xc0000caa80, 0xc000667000, 0x1000, 0x1000, 0xc0006cc8c0, 0x9f, 0x0)
        c:/go/src/io/pipe.go:57 +0xee
io.(*PipeReader).Read(0xc000270150, 0xc000667000, 0x1000, 0x1000, 0xffffffffffffffff, 0x1, 0x7400006f00000001)
        c:/go/src/io/pipe.go:134 +0x53
bufio.(*Reader).fill(0xc0006bbf60)
        c:/go/src/bufio/bufio.go:101 +0x10a
bufio.(*Reader).ReadSlice(0xc0006bbf60, 0xa, 0xffffffffffffffff, 0x88, 0x1000, 0x86, 0xc0006bbe60)
        c:/go/src/bufio/bufio.go:360 +0x45
bufio.(*Reader).ReadLine(0xc0006bbf60, 0xc0000fe5a0, 0x86, 0xc0000fe5a0, 0x86, 0x0, 0x0)
        c:/go/src/bufio/bufio.go:389 +0x3b
github.com/vertcoin-project/one-click-miner-vnext/miners.(*BinaryRunner).launch.func1(0xc0001460f0, 0x1781920, 0xc000270150)
        C:/src/one-click-miner-vnext/miners/miners.go:250 +0xdc
created by github.com/vertcoin-project/one-click-miner-vnext/miners.(*BinaryRunner).launch
        C:/src/one-click-miner-vnext/miners/miners.go:246 +0x350

goroutine 53 [chan receive, 12674 minutes]:
github.com/syossan27/tebata.(*Tebata).listen(0xc0004fe600)
        C:/Users/build/go/pkg/mod/github.com/syossan27/tebata@v0.0.0-20180602121909-b283fe4bc5ba/tebata.go:37 +0x38
created by github.com/syossan27/tebata.New
        C:/Users/build/go/pkg/mod/github.com/syossan27/tebata@v0.0.0-20180602121909-b283fe4bc5ba/tebata.go:30 +0xe7

goroutine 54 [select]:
github.com/wailsapp/wails/lib/event.(*Manager).Start.func1(0xc0001e0050)
        C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/event/manager.go:103 +0x1b4
created by github.com/wailsapp/wails/lib/event.(*Manager).Start
        C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/event/manager.go:99 +0x134

goroutine 55 [select, 8436 minutes]:
github.com/wailsapp/wails/lib/ipc.(*Manager).Start.func1(0xc0001e60c0, 0x178c220, 0xc0004ca000)
        C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/ipc/manager.go:56 +0xf4
created by github.com/wailsapp/wails/lib/ipc.(*Manager).Start
        C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/ipc/manager.go:54 +0x175

goroutine 37 [select]:
github.com/vertcoin-project/one-click-miner-vnext/backend.(*Backend).UpdateLoop(0xc00029e000)
        C:/src/one-click-miner-vnext/backend/update.go:27 +0x127
created by github.com/vertcoin-project/one-click-miner-vnext/backend.(*Backend).WailsInit
        C:/src/one-click-miner-vnext/backend/backend.go:69 +0x7f

goroutine 233 [select, 9983 minutes]:
io.(*pipe).Read(0xc0002f2de0, 0xc00050e000, 0x1000, 0x1000, 0xc000277da0, 0x53, 0x0)
        c:/go/src/io/pipe.go:57 +0xee
io.(*PipeReader).Read(0xc00008a508, 0xc00050e000, 0x1000, 0x1000, 0xf, 0xffffffffffffffff, 0x1)
        c:/go/src/io/pipe.go:134 +0x53
bufio.(*Reader).fill(0xc0000fbf60)
        c:/go/src/bufio/bufio.go:101 +0x10a
bufio.(*Reader).ReadSlice(0xc0000fbf60, 0xa, 0xffffffffffffffff, 0x3c, 0x1000, 0x3a, 0xc000351e60)
        c:/go/src/bufio/bufio.go:360 +0x45
bufio.(*Reader).ReadLine(0xc0000fbf60, 0xc000089300, 0x3a, 0xc000089300, 0x3a, 0x0, 0x0)
        c:/go/src/bufio/bufio.go:389 +0x3b
github.com/vertcoin-project/one-click-miner-vnext/miners.(*BinaryRunner).launch.func1(0xc00085c000, 0x1781920, 0xc00008a508)
        C:/src/one-click-miner-vnext/miners/miners.go:250 +0xdc
created by github.com/vertcoin-project/one-click-miner-vnext/miners.(*BinaryRunner).launch
        C:/src/one-click-miner-vnext/miners/miners.go:246 +0x350

goroutine 173 [select, 12673 minutes]:
io.(*pipe).Read(0xc0008340c0, 0xc0008c5000, 0x1000, 0x1000, 0xc0007ee320, 0xa0, 0x0)
        c:/go/src/io/pipe.go:57 +0xee
io.(*PipeReader).Read(0xc0001da010, 0xc0008c5000, 0x1000, 0x1000, 0xffffffffffffffff, 0x1, 0x7400006f00000001)
        c:/go/src/io/pipe.go:134 +0x53
bufio.(*Reader).fill(0xc000159f60)
        c:/go/src/bufio/bufio.go:101 +0x10a
bufio.(*Reader).ReadSlice(0xc000159f60, 0xa, 0xffffffffffffffff, 0x89, 0x1000, 0x87, 0xc00009fe60)
        c:/go/src/bufio/bufio.go:360 +0x45
bufio.(*Reader).ReadLine(0xc000159f60, 0xc0007fa240, 0x87, 0xc0007fa240, 0x87, 0x0, 0x0)
        c:/go/src/bufio/bufio.go:389 +0x3b
github.com/vertcoin-project/one-click-miner-vnext/miners.(*BinaryRunner).launch.func1(0xc00085c000, 0x1781920, 0xc0001da010)
        C:/src/one-click-miner-vnext/miners/miners.go:250 +0xdc
created by github.com/vertcoin-project/one-click-miner-vnext/miners.(*BinaryRunner).launch
        C:/src/one-click-miner-vnext/miners/miners.go:246 +0x350

goroutine 211 [select, 12673 minutes]:
io.(*pipe).Read(0xc000048360, 0xc0000b3000, 0x1000, 0x1000, 0xc0007e65a0, 0x9f, 0x0)
        c:/go/src/io/pipe.go:57 +0xee
io.(*PipeReader).Read(0xc000006158, 0xc0000b3000, 0x1000, 0x1000, 0xffffffffffffffff, 0x1, 0x7400006f00000001)
        c:/go/src/io/pipe.go:134 +0x53
bufio.(*Reader).fill(0xc0005edf60)
        c:/go/src/bufio/bufio.go:101 +0x10a
bufio.(*Reader).ReadSlice(0xc0005edf60, 0xa, 0xffffffffffffffff, 0x88, 0x1000, 0x86, 0xc000041e60)
        c:/go/src/bufio/bufio.go:360 +0x45
bufio.(*Reader).ReadLine(0xc0005edf60, 0xc0008e4000, 0x86, 0xc0008e4000, 0x86, 0x0, 0x0)
        c:/go/src/bufio/bufio.go:389 +0x3b
github.com/vertcoin-project/one-click-miner-vnext/miners.(*BinaryRunner).launch.func1(0xc00085c000, 0x1781920, 0xc000006158)
        C:/src/one-click-miner-vnext/miners/miners.go:250 +0xdc
created by github.com/vertcoin-project/one-click-miner-vnext/miners.(*BinaryRunner).launch
        C:/src/one-click-miner-vnext/miners/miners.go:246 +0x350

goroutine 64 [chan receive]:
github.com/tidwall/buntdb.(*DB).backgroundManager(0xc0001ea370)
        C:/Users/build/go/pkg/mod/github.com/tidwall/buntdb@v1.1.0/buntdb.go:548 +0xca
created by github.com/tidwall/buntdb.Open
        C:/Users/build/go/pkg/mod/github.com/tidwall/buntdb@v1.1.0/buntdb.go:171 +0x2e5

goroutine 217 [select, 12673 minutes]:
io.(*pipe).Read(0xc000048a20, 0xc0008ea000, 0x1000, 0x1000, 0xc0005f00a0, 0x9f, 0x0)
        c:/go/src/io/pipe.go:57 +0xee
io.(*PipeReader).Read(0xc0000061d0, 0xc0008ea000, 0x1000, 0x1000, 0xffffffffffffffff, 0x1, 0x7400006f00000001)
        c:/go/src/io/pipe.go:134 +0x53
bufio.(*Reader).fill(0xc000783f60)
        c:/go/src/bufio/bufio.go:101 +0x10a
bufio.(*Reader).ReadSlice(0xc000783f60, 0xa, 0xffffffffffffffff, 0x88, 0x1000, 0x86, 0xc0002fde60)
        c:/go/src/bufio/bufio.go:360 +0x45
bufio.(*Reader).ReadLine(0xc000783f60, 0xc0000fe240, 0x86, 0xc0000fe240, 0x86, 0x0, 0x0)
        c:/go/src/bufio/bufio.go:389 +0x3b
github.com/vertcoin-project/one-click-miner-vnext/miners.(*BinaryRunner).launch.func1(0xc00085c000, 0x1781920, 0xc0000061d0)
        C:/src/one-click-miner-vnext/miners/miners.go:250 +0xdc
created by github.com/vertcoin-project/one-click-miner-vnext/miners.(*BinaryRunner).launch
        C:/src/one-click-miner-vnext/miners/miners.go:246 +0x350

goroutine 65148 [IO wait]:
internal/poll.runtime_pollWait(0x1bdfdd07990, 0x72, 0x1782be0)
        c:/go/src/runtime/netpoll.go:222 +0x65
internal/poll.(*pollDesc).wait(0xc0004ce6b8, 0x72, 0x1381400, 0x0, 0x0)
        c:/go/src/internal/poll/fd_poll_runtime.go:87 +0x4c
internal/poll.execIO(0xc0004ce518, 0x1709d50, 0x4d9c6b24f54d701, 0x7ac0de3c24e4480c, 0x55f5b01650f166f0)
        c:/go/src/internal/poll/fd_windows.go:175 +0x105
internal/poll.(*FD).Read(0xc0004ce500, 0xc00067a000, 0xff4, 0xff4, 0x0, 0x0, 0x0)
        c:/go/src/internal/poll/fd_windows.go:441 +0x2ff
net.(*netFD).Read(0xc0004ce500, 0xc00067a000, 0xff4, 0xff4, 0xc00024b6b8, 0x1770735, 0xc00065abe0)
        c:/go/src/net/fd_posix.go:55 +0x56
net.(*conn).Read(0xc00008a4a8, 0xc00067a000, 0xff4, 0xff4, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:182 +0x95
crypto/tls.(*atLeastReader).Read(0xc000262d40, 0xc00067a000, 0xff4, 0xff4, 0x483, 0xfef, 0xc00024b668)
        c:/go/src/crypto/tls/conn.go:779 +0x67
bytes.(*Buffer).ReadFrom(0xc00065ad00, 0x1781440, 0xc000262d40, 0xe9cc0c, 0x14958c0, 0x14f9720)
        c:/go/src/bytes/buffer.go:204 +0xbb
crypto/tls.(*Conn).readFromUntil(0xc00065aa80, 0x1bdfdd07f00, 0xc00008a4a8, 0x5, 0xc00008a4a8, 0x472)
        c:/go/src/crypto/tls/conn.go:801 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc00065aa80, 0x0, 0x0, 0x0)
        c:/go/src/crypto/tls/conn.go:608 +0x12d
crypto/tls.(*Conn).readRecord(...)
        c:/go/src/crypto/tls/conn.go:576
crypto/tls.(*Conn).Read(0xc00065aa80, 0xc000579000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/crypto/tls/conn.go:1252 +0x16d
net/http.(*persistConn).Read(0xc000736120, 0xc000579000, 0x1000, 0x1000, 0xc000746060, 0xc00024bc58, 0xe96dd5)
        c:/go/src/net/http/transport.go:1887 +0x7c
bufio.(*Reader).fill(0xc001c64360)
        c:/go/src/bufio/bufio.go:101 +0x10a
bufio.(*Reader).Peek(0xc001c64360, 0x1, 0x0, 0x0, 0x1, 0x0, 0xc00021c060)
        c:/go/src/bufio/bufio.go:139 +0x56
net/http.(*persistConn).readLoop(0xc000736120)
        c:/go/src/net/http/transport.go:2040 +0x1ba
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:1708 +0xcd7

goroutine 12600 [chan receive]:
github.com/tidwall/buntdb.(*DB).backgroundManager(0xc000368580)
        C:/Users/build/go/pkg/mod/github.com/tidwall/buntdb@v1.1.0/buntdb.go:548 +0xca
created by github.com/tidwall/buntdb.Open
        C:/Users/build/go/pkg/mod/github.com/tidwall/buntdb@v1.1.0/buntdb.go:171 +0x2e5

goroutine 12638 [select, 9982 minutes]:
io.(*pipe).Read(0xc00033a6c0, 0xc00067b000, 0x1000, 0x1000, 0xc00016b0e0, 0x9f, 0x0)
        c:/go/src/io/pipe.go:57 +0xee
io.(*PipeReader).Read(0xc0001da120, 0xc00067b000, 0x1000, 0x1000, 0xffffffffffffffff, 0x1, 0x7400006f00000001)
        c:/go/src/io/pipe.go:134 +0x53
bufio.(*Reader).fill(0xc0005fbf60)
        c:/go/src/bufio/bufio.go:101 +0x10a
bufio.(*Reader).ReadSlice(0xc0005fbf60, 0xa, 0xffffffffffffffff, 0x88, 0x1000, 0x86, 0xc0005fbe60)
        c:/go/src/bufio/bufio.go:360 +0x45
bufio.(*Reader).ReadLine(0xc0005fbf60, 0xc0001623f0, 0x86, 0xc0001623f0, 0x86, 0x0, 0x0)
        c:/go/src/bufio/bufio.go:389 +0x3b
github.com/vertcoin-project/one-click-miner-vnext/miners.(*BinaryRunner).launch.func1(0xc0001460f0, 0x1781920, 0xc0001da120)
        C:/src/one-click-miner-vnext/miners/miners.go:250 +0xdc
created by github.com/vertcoin-project/one-click-miner-vnext/miners.(*BinaryRunner).launch
        C:/src/one-click-miner-vnext/miners/miners.go:246 +0x350

goroutine 12674 [select, 1 minutes]:
github.com/vertcoin-project/one-click-miner-vnext/backend.(*Backend).StartMining.func3(0xc00029e000)
        C:/src/one-click-miner-vnext/backend/mining.go:121 +0x58f
created by github.com/vertcoin-project/one-click-miner-vnext/backend.(*Backend).StartMining
        C:/src/one-click-miner-vnext/backend/mining.go:110 +0x1af

goroutine 12653 [select, 9982 minutes]:
io.(*pipe).Read(0xc001c65c80, 0xc0006ef000, 0x1000, 0x1000, 0xc0005f0140, 0xa0, 0x0)
        c:/go/src/io/pipe.go:57 +0xee
io.(*PipeReader).Read(0xc00008a588, 0xc0006ef000, 0x1000, 0x1000, 0xffffffffffffffff, 0x1, 0x7400006f00000001)
        c:/go/src/io/pipe.go:134 +0x53
bufio.(*Reader).fill(0xc000155f60)
        c:/go/src/bufio/bufio.go:101 +0x10a
bufio.(*Reader).ReadSlice(0xc000155f60, 0xa, 0xffffffffffffffff, 0x89, 0x1000, 0x87, 0xc000155e60)
        c:/go/src/bufio/bufio.go:360 +0x45
bufio.(*Reader).ReadLine(0xc000155f60, 0xc00035e090, 0x87, 0xc00035e090, 0x87, 0x0, 0x0)
        c:/go/src/bufio/bufio.go:389 +0x3b
github.com/vertcoin-project/one-click-miner-vnext/miners.(*BinaryRunner).launch.func1(0xc0001460f0, 0x1781920, 0xc00008a588)
        C:/src/one-click-miner-vnext/miners/miners.go:250 +0xdc
created by github.com/vertcoin-project/one-click-miner-vnext/miners.(*BinaryRunner).launch
        C:/src/one-click-miner-vnext/miners/miners.go:246 +0x350

goroutine 12675 [select]:
github.com/vertcoin-project/one-click-miner-vnext/backend.(*Backend).StartMining.func4(0xc00029e000)
        C:/src/one-click-miner-vnext/backend/mining.go:147 +0x1ea
created by github.com/vertcoin-project/one-click-miner-vnext/backend.(*Backend).StartMining
        C:/src/one-click-miner-vnext/backend/mining.go:130 +0x1d4

goroutine 65149 [select]:
net/http.(*persistConn).writeLoop(0xc000736120)
        c:/go/src/net/http/transport.go:2340 +0x134
created by net/http.(*Transport).dialConn
        c:/go/src/net/http/transport.go:1709 +0xcfc

goroutine 12681 [select]:
io.(*pipe).Write(0xc0000cbf20, 0xc000722000, 0x1, 0x8000, 0x0, 0x0, 0x0)
        c:/go/src/io/pipe.go:94 +0x1e8
io.(*PipeWriter).Write(0xc0002701e0, 0xc000722000, 0x1, 0x8000, 0x1, 0x0, 0x0)
        c:/go/src/io/pipe.go:163 +0x53
io.copyBuffer(0x1781940, 0xc0002701e0, 0x1781e00, 0xc0002701f0, 0xc000722000, 0x8000, 0x8000, 0xc00017c3c0, 0x0, 0x1)
        c:/go/src/io/io.go:411 +0x206
io.Copy(...)
        c:/go/src/io/io.go:368
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
        c:/go/src/os/exec/exec.go:311 +0x6a
os/exec.(*Cmd).Start.func1(0xc0002806e0, 0xc000636fe0)
        c:/go/src/os/exec/exec.go:441 +0x2e
created by os/exec.(*Cmd).Start
        c:/go/src/os/exec/exec.go:440 +0x6b3

goroutine 12682 [syscall, 9982 minutes, locked to thread]:
syscall.Syscall(0x7ff81c644ad0, 0x2, 0xb90, 0xffffffff, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/runtime/syscall_windows.go:188 +0xe9
syscall.WaitForSingleObject(0xb90, 0xffffffff, 0xc000715f98, 0xc000648c00, 0xc000715f28)
        c:/go/src/syscall/zsyscall_windows.go:738 +0x8c
os.(*Process).wait(0xc00001f950, 0x0, 0x0, 0x0)
        c:/go/src/os/exec_windows.go:18 +0x87
os.(*Process).Wait(...)
        c:/go/src/os/exec.go:125
os/exec.(*Cmd).Wait(0xc0002806e0, 0x0, 0x0)
        c:/go/src/os/exec/exec.go:507 +0x67
github.com/vertcoin-project/one-click-miner-vnext/miners.(*BinaryRunner).launch.func2(0xc0001460f0)
        C:/src/one-click-miner-vnext/miners/miners.go:267 +0x39
created by github.com/vertcoin-project/one-click-miner-vnext/miners.(*BinaryRunner).launch
        C:/src/one-click-miner-vnext/miners/miners.go:266 +0x40e

goroutine 12608 [select]:
github.com/vertcoin-project/one-click-miner-vnext/backend.(*Backend).StartMining.func1(0xc00067c7e0, 0xc00029e000)
        C:/src/one-click-miner-vnext/backend/mining.go:53 +0x38f
created by github.com/vertcoin-project/one-click-miner-vnext/backend.(*Backend).StartMining
        C:/src/one-click-miner-vnext/backend/mining.go:36 +0x165

goroutine 12680 [runnable, locked to thread]:
syscall.Syscall6(0x7ff81c644fd0, 0x5, 0x498, 0xc0000a2000, 0x8e, 0xc0000a7af4, 0x0, 0x0, 0x0, 0x0, ...)
        c:/go/src/runtime/syscall_windows.go:201 +0xf2
syscall.WriteFile(0x498, 0xc0000a2000, 0x8e, 0x280, 0xc0000a7af4, 0x0, 0x7ffff80000000000, 0x4)
        c:/go/src/syscall/zsyscall_windows.go:329 +0x105
syscall.Write(0x498, 0xc0000a2000, 0x8e, 0x280, 0x8e, 0x0, 0x0)
        c:/go/src/syscall/syscall_windows.go:394 +0x6f
internal/poll.(*FD).Write(0xc0004ce000, 0xc0000a2000, 0x8e, 0x280, 0x0, 0x0, 0x0)
        c:/go/src/internal/poll/fd_windows.go:620 +0x28d
os.(*File).write(...)
        c:/go/src/os/file_posix.go:48
os.(*File).Write(0xc0001da008, 0xc0000a2000, 0x8e, 0x280, 0x8e, 0x0, 0x0)
        c:/go/src/os/file.go:173 +0x7e
io.(*multiWriter).Write(0xc0001e4d20, 0xc0000a2000, 0x8e, 0x280, 0x1a809e0, 0x0, 0x0)
        c:/go/src/io/multi.go:60 +0x8e
log.(*Logger).Output(0xc00004a050, 0x2, 0xc00028e900, 0x73, 0x0, 0x0)
        c:/go/src/log/log.go:181 +0x294
log.Printf(0xc000279020, 0x1b, 0xc0000a7e50, 0x1, 0x1)
        c:/go/src/log/log.go:320 +0x87
github.com/vertcoin-project/one-click-miner-vnext/logging.Debugf(0x1528778, 0x13, 0xc0000a7e50, 0x1, 0x1)
        C:/src/one-click-miner-vnext/logging/log.go:66 +0x188
github.com/vertcoin-project/one-click-miner-vnext/miners.(*VerthashMinerImpl).ParseOutput(0xc0004f0bf0, 0xc00017cfc0, 0x5a)
        C:/src/one-click-miner-vnext/miners/verthashminer.go:83 +0x99
github.com/vertcoin-project/one-click-miner-vnext/miners.(*BinaryRunner).launch.func1(0xc0001460f0, 0x1781920, 0xc0002701d8)
        C:/src/one-click-miner-vnext/miners/miners.go:255 +0xce
created by github.com/vertcoin-project/one-click-miner-vnext/miners.(*BinaryRunner).launch
        C:/src/one-click-miner-vnext/miners/miners.go:246 +0x350

```

**Comment by gertjaap** [comment]
Fixed in 2.0 rc1
